import Layout from '../../components/main_layout'
import i18n from '../../lib/i18n'
import Head from 'next/head'
import { useRouter } from 'next/router'
import TopComponent from '../../components/main_top_component'
import About from '../../components/home_about'

export default function Carte () {
  const { locale } = useRouter().locale
  return (
    <Layout> <Head>
      <title>{i18n.main.address[locale]}</title>
      <meta name='description'
            content='Generated by create next app'
      />
      <link rel='icon'
            href='/favicon.ico'
      />
    </Head>
      <TopComponent>
     PDF_menu
      </TopComponent>



    </Layout>
  )
}
