import Layout from '../../components/main_layout'
import i18n from '../../lib/i18n'
import Head from 'next/head'
import { useRouter } from 'next/router'
import EventsContainer from '../../components/event_main'
import { responsiveImageFragment } from '../../lib/fragments'
import { request } from '../../lib/datocms'
import { useQuerySubscription } from 'react-datocms'

export async function getStaticProps ({ preview, locale }) {
    const formattedLocale = locale.split('-')[0]
    const graphqlRequest = {
        query: `{
            allEvents(locale: ${formattedLocale}) {
                id
                illustration {
                    responsiveImage(imgixParams: {fm: jpg, fit: crop, w: 2000, h: 1000 }) {
                    ...responsiveImageFragment
                }
            }
            title
            description
            subDescription
            frequency
            day
            frequencyHour
            hour
        }
    }
    ${responsiveImageFragment}
    `,
        preview,
    }
    return {
        props: {
            subscription: preview
                ? {
                    ...graphqlRequest,
                    initialData: await request(graphqlRequest),
                    token: process.env.NEXT_EXAMPLE_CMS_DATOCMS_API_TOKEN,
                    environment: process.env.NEXT_DATOCMS_ENVIRONMENT || null,
                }
                : {
                    enabled: false,
                    initialData: await request(graphqlRequest),
                },
        },
    }
}

export default function Event ({ subscription }) {
    const { locale } = useRouter().locale
    const { data: { allEvents } } = useQuerySubscription(subscription)

    return (
        <Layout> <Head>
            <title>{i18n.main.address[locale]}</title>
            <meta name='description'
                content='Generated by create next app'
            />
            <meta httpEquiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none';" />
            <link rel='icon'
                href='/favicon.ico'
            />
            <link
                href="https://api.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css"
                rel="stylesheet"
            />
        </Head>

        {allEvents.length > 0 && (
            <EventsContainer allEvents={allEvents} />
        )  }

        </Layout>
    )
}
