import Layout from '../../components/main_layout'
import i18n from '../../lib/i18n'
import Head from 'next/head'
import { useRouter } from 'next/router'
import TopComponent from '../../components/main_top-component'
import MiddleComponent from '../../components/main_middle-component'
import Carousel from '../../components/media_carousel-main'
import Gallery from '../../components/media_gallery'

export default function Media () {
  const { locale } = useRouter().locale


  return (
    <Layout> <Head>
      <title>{i18n.main.address[locale]}</title>
      <meta name='description'
            content='Generated by create next app'
      />
      <link rel='icon'
            href='/favicon.ico'
      />
    </Head>

      <TopComponent>
        <Carousel />
      </TopComponent>

      <MiddleComponent>
        <Gallery />
      </MiddleComponent>

      <MiddleComponent>
        Articles
      </MiddleComponent>

    </Layout>
  )
}
