import Layout from '../../components/main_layout'
import i18n from '../../lib/i18n'
import Head from 'next/head'
import TopComponent from '../../components/main_top-component'
import LegacyMain from '../../components/legacy_main'
import { useRouter } from 'next/router'

export default function Carte () {
    const { locales } = useRouter()

    return (
        <Layout>
            <Head>
                <title>{i18n.main.address[locales]}</title>
                <meta name='description'
                    content='Generated by create next app'
                />
                <meta httpEquiv="Content-Security-Policy" content="default-src 'self'; img-src https://*; child-src 'none';" />
                <link rel='icon'
                    href='/favicon.ico'
                />
            </Head>


            <TopComponent>
                <LegacyMain />
            </TopComponent>
        </Layout>
    )
}
